# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_files/server_client.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fproto_files/server_client.proto\"\'\n\x08RootPage\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\"|\n\x0eQueryParameter\x12\x36\n\x0cquery_params\x18\x01 \x03(\x0b\x32 .QueryParameter.QueryParamsEntry\x1a\x32\n\x10QueryParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x94\x02\n\x0c\x45\x63hoResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x13\n\x0bstatus_desc\x18\x02 \x01(\t\x12&\n\x10\x65\x63ho_http_method\x18\x03 \x01(\x0e\x32\x0c.HttpMethods\x12=\n\x11\x65\x63ho_http_headers\x18\x04 \x03(\x0b\x32\".EchoResponse.EchoHttpHeadersEntry\x12\x14\n\x0c\x65\x63ho_payload\x18\x05 \x01(\t\x12*\n\x11\x65\x63ho_query_params\x18\x06 \x01(\x0b\x32\x0f.QueryParameter\x1a\x36\n\x14\x45\x63hoHttpHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\x82\x01\n\x0bHttpMethods\x12\x1b\n\x17HTTP_METHOD_UNSPECIFIED\x10\x00\x12\x13\n\x0fHTTP_METHOD_GET\x10\x01\x12\x14\n\x10HTTP_METHOD_POST\x10\x02\x12\x13\n\x0fHTTP_METHOD_PUT\x10\x03\x12\x16\n\x12HTTP_METHOD_DELETE\x10\x04\x42\x1cZ\x1ahttpserver/golang/protobufb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_files.server_client_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\032httpserver/golang/protobuf'
  _QUERYPARAMETER_QUERYPARAMSENTRY._options = None
  _QUERYPARAMETER_QUERYPARAMSENTRY._serialized_options = b'8\001'
  _ECHORESPONSE_ECHOHTTPHEADERSENTRY._options = None
  _ECHORESPONSE_ECHOHTTPHEADERSENTRY._serialized_options = b'8\001'
  _HTTPMETHODS._serialized_start=482
  _HTTPMETHODS._serialized_end=612
  _ROOTPAGE._serialized_start=35
  _ROOTPAGE._serialized_end=74
  _QUERYPARAMETER._serialized_start=76
  _QUERYPARAMETER._serialized_end=200
  _QUERYPARAMETER_QUERYPARAMSENTRY._serialized_start=150
  _QUERYPARAMETER_QUERYPARAMSENTRY._serialized_end=200
  _ECHORESPONSE._serialized_start=203
  _ECHORESPONSE._serialized_end=479
  _ECHORESPONSE_ECHOHTTPHEADERSENTRY._serialized_start=425
  _ECHORESPONSE_ECHOHTTPHEADERSENTRY._serialized_end=479
# @@protoc_insertion_point(module_scope)
